serenditree:
  log:
    level: INFO
    pretty: false
    properties: false
  fence:
    verification:
      paths: /api/v1/user/verify/callback/*
      scopes: profile,openid
    policies:
      enabled: false
    cronjobs:
      cleanup: 0 2 * * *
    error: "Unhandled error during authentication and authorization."
  root:
    user:
      user: ~
      password: ~
    seed:
      user: ~
      password: ~
quarkus:
  application:
    name: branch-user
  datasource:
    db-kind: postgresql
    username: ${serenditree.root.user.user}
    password: ${serenditree.root.user.password}
    jdbc:
      telemetry: true
      url: jdbc:postgresql://root-user:5432/serenditree
  hibernate-orm:
    scripts:
      generation: none
    jdbc:
      statement-batch-size: 100
      statement-fetch-size: 100
    quote-identifiers:
      strategy: all
    log:
      jdbc-warnings: true
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{3.}] (%t) %s%e%n"
    category:
      "io.smallrye.health":
        level: WARN
      "io.opentelemetry":
        level: WARN
      "io.serenditree":
        level: ${serenditree.log.level}
  otel:
    enabled: true
    traces:
      sampler: traceidratio
    exporter:
      otlp:
        traces:
          endpoint: ~
  oidc:
    at:
      auth-server-url: ~
      application-type: web-app
      client-id: ~
      credentials:
        secret: ~
      authentication:
        scopes: ${serenditree.fence.verification.scopes}
    auth-server-url: ${quarkus.oidc.at.auth-server-url}
    application-type: ${quarkus.oidc.at.application-type}
    client-id: ${quarkus.oidc.at.client-id}
    credentials:
      secret: ${quarkus.oidc.at.credentials.secret}
    authentication:
      scopes: ${quarkus.oidc.at.authentication.scopes}
  smallrye-openapi:
    path: /api/v1/user/openapi
  swagger-ui:
    always-include: false
    path: /api/v1/user/swagger
  scheduler:
    cron-type: unix
  shutdown:
    timeout: 10
  http:
    auth:
      permission:
        authenticated:
          paths: ${serenditree.fence.verification.paths}
          policy: authenticated
mp:
  messaging:
    outgoing:
      user-deleted:
        bootstrap:
          servers: root-wind:9092
        connector: smallrye-kafka
        key:
          serializer: org.apache.kafka.common.serialization.LongSerializer
        value:
          serializer: org.apache.kafka.common.serialization.LongSerializer
