# see serenditree.yml in project root
quarkus:
  mongodb:
    credentials:
      username: ${serenditree.root.seed.user}
      password: ${serenditree.root.seed.password}
      auth-mechanism: SCRAM-SHA-256
    database: serenditree
    hosts:
      - root-seed-0.root-seed-headless:27017
      - root-seed-1.root-seed-headless:27017
  log:
    category:
      "org.mongodb.driver":
        level: INFO
